export const AuthRoute = '/authentication'
export const HomeRoute = '/'
export const RegisterRoute = '/registration'
export const ProfilesRoute = '/profiles'
export const ProductsRoute = '/products'
export const AboutRoute = '/about'